---
- name: Create your user
  hosts: all
  become: yes
  gather_facts: true

  tasks:
          - include_vars: var.yml

          - group:
              name: sudo
              state: present

          - name: Create and add user
            user: 
              name: "{{ username }}"
              shell: /bin/bash
              createhome: yes 
              comment: "create with ansible"
            become: yes
            become_method: "sudo"

          - name: setup the authorized key
            authorized_key: 
              user: "{{ username }}" 
              key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
