---
- name: Update your VM
  hosts: all
  gather_facts: true
  become: yes

  tasks:

    - include_vars: version.yml

    - name: Update yum
      yum:
              name: "*"
              state: latest

    - name: Download Openjdk-{{java_version}}
      get_url:
              url: https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz  #Openjdk links are different from each other, we have to manually put the link here.
              dest: /opt
              mode: '0755'
              group: sudo
              owner: jboss
              timeout: 20

    - name: extract Openjdk-{{java_version}} tar file
      unarchive:
              src: /opt/openjdk-{{java_version}}_linux-x64_bin.tar.gz
              dest: /opt
              remote_src: True

    - name: Removing Openjdk-{{java_version}} tar file
      file:
              path: /opt/openjdk-{{java_version}}_linux-x64_bin.tar.gz
              state: absent

    - name: Renaming the Openjdk-{{java_version}} file
      command: mv /opt/jdk-{{java_version}} /opt/java

    - name: Download the apache maven-{{maven_version}} tar file
      get_url:
              url: "{{maven_download_url}}"
              dest: /opt
              mode: '0755'
              group: sudo
              owner: jboss
              timeout: 20

    - name: extract maven-{{maven_version}} tar file
      unarchive:
              src: /opt/apache-maven-{{maven_version}}-bin.tar.gz
              dest: /opt
              remote_src: True

    - name: Removing maven-{{maven_version}} tar file
      file:
              path: /opt/apache-maven-{{maven_version}}-bin.tar.gz
              state: absent

    - name: Renaming the maven-{{maven_version}} file
      command: mv /opt/apache-maven-{{maven_version}} /opt/maven

    - name: create jboss user directory
      file:
        path: /jboss
        state: directory
        mode: '0777'
        group: sudo
        owner: jboss

    - name: create .bashrc file
      file:
        path: "/jboss/.bashrc"
        state: touch
        mode: '0777'
        group: sudo
        owner: jboss

    - name: set environment variable for java and maven
      blockinfile: 
        path: /jboss/.bashrc
        insertafter: 'EOF'
        block: |
                export JAVA_HOME=/opt/java
                export PATH="$JAVA_HOME/bin:$PATH:/opt/maven/bin"
        state: present

    - name: source the bashrc file
      shell: source /jboss/.bashrc
      owner: jboss
      group: sudo
